- name: "TEST HTTPS SSH TUNNEL"
  hosts: all
  gather_facts: false
  vars_files: .vault/admin.secret
  roles:
    - common
  tasks:

    - name: Get firmware version using bigip_command module
      f5networks.f5_modules.bigip_command:
        commands: show sys version
        provider: "{{ provider }}"
      timeout: 30
      register: my_result
      delegate_to: "{{ execution_host }}"

    - name: wait for remote node online on port 443
      f5networks.f5_modules.bigip_wait:
        delay: 5
        timeout: 300
        provider: "{{ provider }}"
      delegate_to: "{{ execution_host }}"