- name: Deploy OpenShift 4.14 on Baremetal (KVM)
  hosts: all
  gather_facts: false
  roles:
    - create_kvm_infra
    # - OCP002_setup_ocp_bastion
    # - OCP003_deploy_ocp_cluster

  tasks:

    - name: 1.1. Creating LibVirt Network Bridge for the OpenShift Cluster
      community.libvirt.virt_net:
        state: present
        autostart: true
        name: "{{ create_kvm_infra_net_bridge_name }}"
        xml: "{{ lookup('template', 'network_bridge.j2') }}"

    - name: sssss
      debug:
        msg: hey yo!
